name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: macos-latest
    # Only build for the native architecture for now
    # Cross-compilation for macOS frameworks is complex
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.0
    
    - name: Build Release
      run: |
        zig build -Doptimize=ReleaseFast
        # GitHub Actions runs on x86_64 for now
        mv zig-out/bin/skhd skhd-x86_64-macos
    
    - name: Create tarball
      run: |
        tar -czf skhd-x86_64-macos.tar.gz skhd-x86_64-macos
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./skhd-x86_64-macos.tar.gz
        asset_name: skhd-x86_64-macos.tar.gz
        asset_content_type: application/gzip

